import { Record } from '@servicenow/sdk/core'

export default Record({
    $id: 'ca224c3e533132102a1279b0a0490e39',
    table: 'sysevent_email_action',
    data: {
        action_insert: false,
        action_update: true,
        active: true,
        category: 'c97d83137f4432005f58108c3ffa917a',
        collection: 'incident',
        condition: 'stateVALCHANGES^EQ',
        content_type: 'text/html',
        digest_separator_html: '<br><hr><br>',
        digest_separator_text: '\\n--------------------------------------------------------------------------------\\n',
        digestable: false,
        enable_dynamic_translation: false,
        event_parm_1: false,
        event_parm_2: false,
        exclude_delegates: false,
        force_delivery: false,
        generation_type: 'engine',
        include_attachments: false,
        item: 'event.parm1',
        mandatory: false,
        name: 'Incident state changes',
        omit_watermark: false,
        order: 100,
        push_message_only: true,
        recipient_users: '6816f79cc0a8016401c5a33be04be441',
        send_self: true,
        subscribable: false,
        sys_domain: 'global',
        sys_domain_path: '/',
        sys_name: 'Incident state changes',
        sys_version: 2,
        type: 'email',
        weight: 0,
    },
})
